name: cep_finder
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  bloc: ^8.1.4
  brasil_fields: ^1.15.0
  cupertino_icons: ^1.0.8
  cloud_firestore: ^5.5.0
  equatable: ^2.0.7
  fake_cloud_firestore: ^3.1.0
  flutter_bloc: ^8.1.6
  firebase_core: ^3.8.0
  flutter_svg: ^2.0.16
  get_it: ^8.0.2
  go_router: ^14.6.1
  google_maps_flutter: ^2.10.0
  http: ^1.2.2
  lottie: ^3.1.3
  mocktail: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  bloc_test: ^9.1.7
  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/lottie/
    - assets/icons/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 700